# Generated by Django 5.1 on 2024-08-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linux', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdomain',
            name='url',
        ),
    ]
