# Generated by Django 5.1 on 2024-08-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(choices=[('django.core.mail.backends.smtp.EmailBackend', 'SMTP'), ('django.core.mail.backends.console.EmailBackend', 'Console'), ('django.core.mail.backends.filebased.EmailBackend', 'File-based')], default='django.core.mail.backends.smtp.EmailBackend', max_length=255)),
                ('email_service', models.CharField(blank=True, choices=[('Gmail', 'Gmail'), ('Outlook', 'Outlook'), ('Yahoo Mail', 'Yahoo Mail'), ('Zoho Mail', 'Zoho Mail'), ('GMX', 'GMX'), ('AOL Mail', 'AOL Mail'), ('ProtonMail', 'ProtonMail'), ('SMTP2GO', 'SMTP2GO'), ('SendPulse', 'SendPulse'), ('MailerSend', 'MailerSend'), ('Mailtrap', 'Mailtrap'), ('Postmark', 'Postmark'), ('SendGrid', 'SendGrid'), ('Manual', 'Manual')], max_length=255, null=True)),
                ('email_host', models.CharField(blank=True, max_length=255, null=True)),
                ('email_port', models.IntegerField(blank=True, null=True)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('email_host_user', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_host_password', models.CharField(blank=True, max_length=255, null=True)),
                ('default_from_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
